id: P004162
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:27.616001
source_metadata:
  id: bdr:W1KG11733
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་རྣམ་གཉིས་ཀྱི་དཀའ་གནད་གསལ་བར་བྱེད་པ་ལེགས་བཤད་སྐལ་བཟང་ཀླུ་དབང་གི་རོལ་མཚོ།
    ༼དགའ་ལྡན་པར་མ།༽
  author: ''
  volumes:
    ac121b6b227941fda48d24634b182074:
      image_group_id: I1KG11739
      title: ''
      volume_number: 1
      total_pages: 820
      base_file: v001.txt
    b4f656bcc6474506b2f40a1ed8f478ca:
      image_group_id: I1KG11740
      title: ''
      volume_number: 2
      total_pages: 1152
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
