id: opecha:P004162
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11733
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་རྣམ་གཉིས་ཀྱི་དཀའ་གནད་གསལ་བར་བྱེད་པ་ལེགས་བཤད་སྐལ་བཟང་ཀླུ་དབང་གི་རོལ་མཚོ།
    ༼དགའ་ལྡན་པར་མ།༽
  volume: ''
  author: ''
