id: I59913939
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:19:39+00:00'
last_modified: '2022-06-07T20:42:54.622997+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11733
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་རྣམ་གཉིས་ཀྱི་དཀའ་གནད་གསལ་བར་བྱེད་པ་ལེགས་བཤད་སྐལ་བཟང་ཀླུ་དབང་གི་རོལ་མཚོ།
    ༼དགའ་ལྡན་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3419':
      image_group_id: I1KG11739
      title: ''
      total_pages: 820
      order: 1
      base_file: 3419.txt
    6A81:
      image_group_id: I1KG11740
      title: ''
      total_pages: 1152
      order: 2
      base_file: 6A81.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
