id: I59913939
legacy_id: P004162
ocr_import_info:
  bdrc_scan_id: W1KG11733
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T09:11:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:03:12.376393+00:00'
last_modified: 2022-08-31 11:04:19.647015
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11733
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11733
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་རྣམ་གཉིས་ཀྱི་དཀའ་གནད་གསལ་བར་བྱེད་པ་ལེགས་བཤད་སྐལ་བཟང་ཀླུ་དབང་གི་རོལ་མཚོ།
    ༼དགའ་ལྡན་པར་མ།༽
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.653959981699755
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I1KG11739:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11739
      total_pages: 820
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11739.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6436824236963775
    legacy_id: v001
  I1KG11740:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11740
      total_pages: 1152
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG11740.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6615155793658234
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
